[[redirects]]
  from = "/"
  to = "/codeway.html"
  status = 200

[[redirects]]
  from = "/mgmt"
  to = "/mgmt.html"
  status = 200

[[redirects]]
  from = "/codeway-management"
  to = "/mgmt"
  status = 301
