[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/metrics"
  to   = "/.netlify/functions/get-metrics"
  status = 200

[[redirects]]
  from = "/"
  to = "/mgmt.html"
  status = 200

[[redirects]]
  from = "/mgmt"
  to = "/mgmt.html"
  status = 200

[[redirects]]
  from = "/codeway-management"
  to = "/mgmt.html"
  status = 301
